#docker-compose.yaml
version: '3'

#Spring Boot service
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      working_dir: /var/www
      volumes:
        - ./:/var/www
          #They bind-mount their ./php/local.ini to /usr/local/etc/php/conf.d/local.ini here, similar we would probably also add the source here for the app.
          #https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose-on-ubuntu-20-04
      networks:
        - app-network

#Nginx Service
    webserver:
      image: nginx:1.23.1-alpine
      container_name: webserver
      restart: always
      tty: true
      ports:
        - "8080:80"
      depends_on:
        - app
      volumes: 
        - ./:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
      links:
        - app
      networks:
        - app-network

#PostgreSQL Service
    db:
      image: postgres:14.1-alpine
      container_name: db
      restart: always
      volumes:
        - db_data:/var/lib/postgresql/data
        - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      command: postgres -c config_file=/etc/postgresql/postgresql.conf
      environment:
        POSTGRES_PASSWORD:
        POSTGRES_USER:
        POSTGRES_DB:
      ports:
        - "54320:5432"
      networks:
        - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
  db_data:
    driver: local
