#docker-compose.yaml
version: '3'

#Spring Boot service
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      #target: dev
    container_name: backend
    tty: true
    depends_on:
      - database
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    expose:
      - "8080"
    volumes:
      - ./resources:/res
    networks:
      - app-network

#Nginx Service
  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: always
    tty: true
    ports:
    - "80:80"
    depends_on:
    - backend
    volumes: 
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - backend
    networks:
      - app-network

#PostgreSQL Service
  database:
    environment:
      POSTGRES_PASSWORD: secret 
      POSTGRES_DB: openlifedb
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - app-network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: always
    depends_on:
      - database
    ports:
      - "5555:80"
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace 
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
  db-data:
    driver: local
  cloudbeaver:
