#docker-compose.yaml
version: '3'

#Spring Boot service
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    depends_on:
      - postgres 
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      #credentials for database access.
      #SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/openlifedb
      #SPRING_DATASOURCE_USERNAME: admin
      #SPRING_DATASOURCE_PASSWORD: secret
      #SPRING_JPA_HIBERNATE_DDL_AUTO: update
      #it could be argued that our working directory should be in ./app
      working_dir: /usr/local/dev/OpenLife/
    expose:
      - "8080"
    volumes:
      - ./:/var/www
          #They bind-mount their ./php/local.ini to /usr/local/etc/php/conf.d/local.ini here, similar we would probably also add the source here for the app.
          #https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose-on-ubuntu-20-04
    networks:
      - app-network

#Nginx Service
  proxy:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: proxy
    restart: always
    tty: true
    ports:
    - "80:80"
    depends_on:
    - app
    volumes: 
      - ./:/var/www
    links:
      - app
    networks:
      - app-network

#PostgreSQL Service
  postgres:
    environment:
      POSTGRES_PASSWORD: secret 
      POSTGRES_DB: openlifedb
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - app-network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: always
    depends_on:
      - postgres
    ports:
      - "5555:80"
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace 
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
  db-data:
    driver: local
  cloudbeaver:
